import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { CircleCheck, CircleX } from "lucide-react";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interSans.variable} antialiased`}>
        <Toaster
          icons={{
            error: <CircleX className="text-destructive size-5" />,
            success: <CircleCheck className="text-green-700 size-5" />,
          }}
        />
        {children}
      </body>
    </html>
  );
}
